### ISSUE TITLE
Can't open configuration in admin page after install magento-chatbot

### ISSUE THREAD

**Issue by huynit** [blopa/Magento-Chatbot#142]
Hi . after install module i can't open frontend page and configuration in admin page, i chek in report folder i found error is "Undefined index: id", Please see in attach file .
[804580717750.txt](https://github.com/blopa/Magento-Chatbot/files/1608530/804580717750.txt)

Do you have any solution for it?

**Comment by blopa** [comment]
Hello @huynit, how are you?

Are you using Magento 1 or Magento 2 version?

Best.

**Comment by huynit** [comment]
Thank for reply.I using magento 2, i try install and reinstall again but
still error
You have any solution?

Vào 6 thg 1, 2018 10:39 CH, "Pablo Benmaman" <notifications@github.com> đã
viết:

Hello @huynit <https://github.com/huynit>, how are you?

Are you using Magento 1 or Magento 2 version?

Best.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blopa/Magento-Chatbot/issues/142#issuecomment-355754765>,
or mute the thread

**Comment by blopa** [comment]
I'll have a look

**Comment by blopa** [comment]
Can you send me your var/log and var/report folders?

**Comment by blopa** [comment]
Which module version are you using?

**Comment by huynit** [comment]
I using last version 2.2.2 of magento , if you need i'll send source code
for you

Vào 6 thg 1, 2018 11:49 CH, "Pablo Benmaman" <notifications@github.com> đã
viết:

Can you send me your var/log and var/report folders?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blopa/Magento-Chatbot/issues/142#issuecomment-355759391>,
or mute the thread

**Comment by huynit** [comment]
I uninstall version error and clear all error. If you want log or report,
i'll install it again if you need

Vào 7 thg 1, 2018 12:02 SA, "Đức Huy" <huyit.nguyen@gmail.com> đã viết:

I using last version 2.2.2 of magento , if you need i'll send source code
for you

Vào 6 thg 1, 2018 11:49 CH, "Pablo Benmaman" <notifications@github.com> đã
viết:

Can you send me your var/log and var/report folders?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blopa/Magento-Chatbot/issues/142#issuecomment-355759391>,
or mute the thread

**Comment by blopa** [comment]
I mean, what version of the module are you using? Latest 1.0.5?

**Comment by huynit** [comment]
Yes i using last version of module

Vào 7 thg 1, 2018 12:24 SA, "Pablo Benmaman" <notifications@github.com> đã
viết:

**Comment by blopa** [comment]
Try this version and let me know: https://github.com/blopa/Magento-Chatbot/archive/feature/update_description.zip

**Comment by hafeez3000** [comment]
Works like a charm!

**Comment by huynit** [comment]
Sorry . i go out now. I will try  later.

Vào 7 thg 1, 2018 12:48 SA, "Abdul Hafeez" <notifications@github.com> đã
viết:

Works like a charm!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blopa/Magento-Chatbot/issues/142#issuecomment-355763189>,
or mute the thread

**Comment by blopa** [comment]
Ok, please let me know so I can merge the code.

**Comment by huynit** [comment]
hi blopa.
i'll install your update packet but still error. you can link to "www.noithatsaigoncaocap.com" frontend not load after i install module, maybe i need clear cache ?
i install step by step like this:

> #List all modules
> php -f bin/magento module:status
> #Enable magento-chatbot module
> php -f bin/magento module:enable Werules_Chatbot --clear-static-content
> #Run database installation upgrades
> php -f bin/magento setup:upgrade
> #Compile 
> php -f bin/magento setup:di:compile
> #Deploy Static Content 
> php -f bin/magento setup:static-content:deploy

it's correct step ?

**Comment by hafeez3000** [comment]
Hi Huynit,  Look for any issues with file permissions

**Comment by huynit** [comment]
hi hafeez3000 
what yow meant? 
i don't know exactly your module need permission. can you check it in my cpanel

**Comment by blopa** [comment]
That doesn't look like a error from the module. Did you installation worked before installing the module? Can you send me the log?

**Comment by huynit** [comment]
hi blopa 
you mean worked is crontab ?
[log.zip](https://github.com/blopa/Magento-Chatbot/files/1609788/log.zip)

**Comment by blopa** [comment]
That doesn't look like a error from the module. Try installing the module in a new M2 instance.
