### ISSUE TITLE
How to setup and configure in facebook need proper document

### ISSUE THREAD

**Issue by techzotezo** [blopa/Magento-Chatbot#143]
Hi,
In order to implement chatbot we need to configure facebook properly.
Please provide us the document or manual so that I can configure it...

Thanks

**Comment by techzotezo** [comment]
I have seen this https://blopa.github.io/docs/magento_chatbot/#facebook_configuration but in facebook apps I cannot able to configure.Please help me in this concern...

**Comment by blopa** [comment]
Hello @techzotezo. You're right. The current documentation is old, I'll work on a new one this weekend.

**Comment by techzotezo** [comment]
Actually I have already set it up in my magento store but cannot able to configure facebook. Please provide us relevant documents so that I can configure...

**Comment by techzotezo** [comment]
Can you update the documents so that I can configure facebook properly?Actually I want to launch the module in this week.

**Comment by blopa** [comment]
Hello @techzotezo.
What is your problem exactly? Could you explain in a more specific way so I can try to help you better.

**Comment by YannigSmagghe** [comment]
Hi, I need help too with facebook configuration.

I'm stuck on webhook conf, what is the callback url ? Facebook told me 404, i gave this :
"https://magento2-app/chatbot/webhook/endpoint/api/messenger/key/dhfo983rf0j"

dhfo983rf0j is my token set on general settings as Your Secret Key.

Can you help me plz ?

**Comment by blopa** [comment]
Hi @YannigSmagghe. `magento2-app` dosen't seems like a valid web address. Can you try deploying in a valid web address?

**Comment by blopa** [comment]
Please update to version 1.0.7
