### ISSUE TITLE
Messenger Settings Not Loaded

### ISSUE THREAD

**Issue by ntan-vixi** [blopa/Magento-Chatbot#146]
Hello,

I have a problem with my Magento 2 shop, the Messenger Settings page is not loaded.
But the general settings page is working fine.

![image](https://user-images.githubusercontent.com/33009981/36663090-e8dececa-1af9-11e8-9e5d-5fb2eb0c508e.png)

**Comment by blopa** [comment]
Hi there.

That's weird. What is your Magento version? Can you send me your log files?

**Comment by ntan-vixi** [comment]
Hello, 

I didn't see any error about the application. I'm sending you the log files anyway.

I am using Magento 2

Thanks,

**Comment by ntan-vixi** [comment]
[log.zip](https://github.com/blopa/Magento-Chatbot/files/1758668/log.zip)
[report.zip](https://github.com/blopa/Magento-Chatbot/files/1758670/report.zip)

**Comment by syntaxisarg** [comment]
the same thing happens with magento 2.2.2

**Comment by itsmudassir** [comment]
I am using Magento 2.2.3 i extracted the chatbot zip in the magento root directory and did the four installation steps but I can not even see it in the store . Please help . I compiled the whole magento directory with [ sudo php bin/magento setup:di:compile  ] as the 4th step of installation. Please help.
![magnro](https://user-images.githubusercontent.com/10288897/36971647-5085acb2-208e-11e8-86bf-ff595a4ec6b3.png)

**Comment by itsmudassir** [comment]
@ntan-vixi  Can you please tell me the installation steps for this chatbot on magento 2 as there is no [ System > General Settings > Chatbot Settings ] to be found .

**Comment by ntan-vixi** [comment]
@itsmudassir You can follow the steps indicated in page 4 of this pdf https://www.mageworx.com/index.php/downloads/dl/file/id/124/product/0/woxy_user_guide_10_17.pdf

**Comment by blopa** [comment]
Hey guys. Just a quick update that I didn't forgot about this issue. I looked over at this on the weekend, but couldn't find any problems. I'll keep looking until I find a solution.

**Comment by itsmudassir** [comment]
@ntan-vixi   same Messenger-setting disappearing error happens  when I use my server url as localhost/magento/admin  and its doesnt happen when i use server url as 127.0.0.1/magento .

**Comment by itsmudassir** [comment]
@blopa  @ntan-vixi  how do you guys use it locally ? for other bots development Ngrok works for ssl problem . Do you guy use ngrok for local development?
I have tried to use ngrok but it doesnt work completely for me .

**Comment by xmav** [comment]
Looks like issue comes from app/code/Werules/Chatbot/etc/config.xml
It cannot read value for <commands_list>. I have commented that field in config.xml and get  all fields in backend config visible (Messenger Settings)

**Comment by blopa** [comment]
@xmav What version of Magento are you using?

@itsmudassir @ntan-vixi @syntaxisarg could you try @xmav solution? I'm still not able to reproduce the problem, but this seems like a good lead.

**Comment by blopa** [comment]
You guys cal also try running this command:


`php bin/magento cache:flush;php bin/magento cache:clean;php bin/magento setup:upgrade;php bin/magento setup:static-content:deploy -f`

**Comment by xmav** [comment]
@blopa I am testing it using Magento 2.2.2

**Comment by blopa** [comment]
Local machine? Windows or Linux?

**Comment by xmav** [comment]
local dev environment on Ubuntu with Apache and PHP 7.0.25

**Comment by xmav** [comment]
@blopa To reproduce issue make sure that you don't have value for "commands_list" field in database core_config_data table. In this case default values from config.xml will be used and I hope you will see the issue

**Comment by xmav** [comment]
Here is more info from me:
Looks like thats breaking changes in Magento 2.2 and 2.3
https://github.com/magento/magento2/commit/3f5494763b4d7095d51fac44b4cd4dc4a6ab4b92#diff-6b58c5ee8a358659b65e043f71bca51b
As you may see in 2.2 \Magento\Framework\Serialize\Serializer\Json used as serializer. Thats why it cannot unserialize your value from config.xml

**Comment by blopa** [comment]
I'm waiting for the others to confirm if that fixed their problem, and I'll release a new version.

**Comment by itsmudassir** [comment]
Yes commenting the <commands_list> in config.xml solves the disappearing menu problem . but now the module is connected and my webhook url gives 404 error please take a look @blopa . I am using latest magento2 and the chatbox appears in home but the webhook doesnt work I tried to add a '/' at the end as well .
![1](https://user-images.githubusercontent.com/10288897/37679299-531fb326-2ca2-11e8-841d-e80cb5df646f.PNG)
![2](https://user-images.githubusercontent.com/10288897/37679300-535de8b2-2ca2-11e8-8e4d-014048335af1.PNG)

**Comment by itsmudassir** [comment]
@xmav did  commenting the <commands_list> in config.xml  solve your problem ? for It does make the settings visible but the extension does not generate working facebook webhook   URL. If it worked for you please tel me your magento version and how did you host  it with SSL .

**Comment by blopa** [comment]
@itsmudassir Try http://mudassir.website/chatbot/webhook/messenger/endpoint/al1foqt1ts

**Comment by blopa** [comment]
Version 1.0.7 released! https://github.com/blopa/Magento-Chatbot/releases/tag/m2_v1.0.7

**Comment by babybeddingdesign** [comment]
Hi,
this VER will work on magento 2.3?
