### ISSUE TITLE
Messenger Settings Fatal Error

### ISSUE THREAD

**Issue by YannigSmagghe** [blopa/Magento-Chatbot#148]
Hi guys, your project look nice but i have this bug on Messenger Settings from admin pannel

`1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /data/demo/src/current/app/code/Magento/Config/Model/Config/Backend/Serialized.php(55): Magento\Framework\Serialize\Serializer\Json->unserialize('\n\t\t\t\t\ta:16:{s:1...')
#1 /data/demo/src/current/lib/internal/Magento/Framework/Model/AbstractModel.php(601): Magento\Config\Model\Config\Backend\Serialized->_afterLoad()
#2 /data/demo/src/current/generated/code/Magento/Config/Model/Config/Backend/Serialized/ArraySerialized/Interceptor.php(323): Magento\Framework\Model\AbstractModel->afterLoad()
#3 /data/demo/src/current/app/code/Magento/Config/Block/System/Config/Form.php(441): Magento\Config\Model\Config\Backend\Serialized\ArraySerialized\Interceptor->afterLoad()
#4 /data/demo/src/current/app/code/Magento/Config/Block/System/Config/Form.php(349): Magento\Config\Block\System\Config\Form->getFieldData(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), 'werules_chatbot...')
#5 /data/demo/src/current/app/code/Magento/Config/Block/System/Config/Form.php(325): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'werules_chatbot...', '', '')`

Any idea ?

**Comment by blopa** [comment]
Did you got it working?
