### ISSUE TITLE
Not replying

### ISSUE THREAD

**Issue by bloggerpact** [blopa/Magento-Chatbot#60]
First of all, i would like to say thanks for making this open-source bot for Magento.
**I integrated all the setting** Please check ss below

![image](https://user-images.githubusercontent.com/22036537/26996877-160efaf8-4d93-11e7-9ac5-7e01a2c70cc0.png)

![image](https://user-images.githubusercontent.com/22036537/26996865-00dd346a-4d93-11e7-91f8-3fe02165d080.png)

![image](https://user-images.githubusercontent.com/22036537/26996909-53e6feb6-4d93-11e7-8d95-363ba238f76f.png)
![image](https://user-images.githubusercontent.com/22036537/26996914-5d568d86-4d93-11e7-8d43-f26fe5ec89c6.png)

**I have tried to message bot via my own account, it's not replying. :(** 

![image](https://user-images.githubusercontent.com/22036537/26996888-2776d464-4d93-11e7-9494-32ba033abc97.png)

If you can help me It will be appreciated. In waiting for your quick response. @blopa 

Thanks

**Comment by blopa** [comment]
Hello. I'm sorry you're having problems with my extension, I'm actually travelling out of my country and I don't have my computer with me, so I can't help you right now, but I'll do as soon as possible. 

While you wait you should have a look at this issue https://github.com/blopa/Magento-Chatbot/issues/31 might help you.

**Comment by blopa** [comment]
Hello. Did you managed to get it to work? Please let me know.

**Comment by bloggerpact** [comment]
Hey,

Problem is still there. It looks like the FB backend app setting is OK but do not know what's wrong. If you can help me It will be appreciated. In waiting for your quick response. @blopa 

Thanks

**Comment by blopa** [comment]
Hello.

Did you setup the secret key correctly? I think that maybe you're missing some configuration on Facebook Developer website. My documentation is incomplete, I'll work on that the next weeks. Try following this tutorial starting from step #3: https://blog.hartleybrody.com/fb-messenger-bot/. You're probably missing the "Generate a Page Access Token" part.

Best

**Comment by bloggerpact** [comment]
Hey,

**Yes i did, Please ss below both secret key and page access token generated correctly** 

![image](https://user-images.githubusercontent.com/22036537/27765419-de73741a-5ecd-11e7-85e4-a938d4c01afb.png)

**Back-end setting** 

![image](https://user-images.githubusercontent.com/22036537/27765421-f5c1a4d4-5ecd-11e7-984f-f0c05a2256bf.png)

Thanks,

--- Little Update ---

_There was little issue about Messenger username. I fixed it_ But **problem** still there

In waiting for your quick response. @blopa

**Comment by blopa** [comment]
Hello. Got it. So the problem must be in the Webhook setup, your Facebook verify token must be the same as you custom key (general config). Try that and let me know.

**Comment by bloggerpact** [comment]
Hey,

**I've already done this. I'm attaching screenshots please check Below:** 

![image](https://user-images.githubusercontent.com/22036537/27765613-e248edb2-5ed3-11e7-9e07-39f7c72e6cda.png)

![image](https://user-images.githubusercontent.com/22036537/27765591-30f0553c-5ed3-11e7-8d2f-02ed89abddf6.png)

![image](https://user-images.githubusercontent.com/22036537/27765594-543f0150-5ed3-11e7-885f-65a70a97e3c8.png)

**It shows "complete"**

In waiting for your quick response. @blopa

**Comment by blopa** [comment]
Well that's very weird... would you mind sending me access to your Magento installation so I can have a look?

http://www.pablomontenegro.com.br/contato/

**Comment by bloggerpact** [comment]
Hey,

Back-end Login Has sent to you.  Please check @blopa

**Comment by blopa** [comment]
So you were missing a "**/**" in the end of the webhook URL:

Your webhook was set as https://mystore.com/chatbot/chatdata/facebook/key/SECRET_KEY and it should be https://mystore.com/chatbot/chatdata/facebook/key/SECRET_KEY/

Please don't forget to give this extension a star and share it with your Magento buddies :D

Best.

**Comment by bloggerpact** [comment]
well, it started working but another issue has come : 

![image](https://user-images.githubusercontent.com/22036537/27791684-ef2dd20e-6013-11e7-8e73-43cf5d4e7c16.png)

It was working fine but I sent a checkout command, after it started to give me an error. 
In waiting for your quick response. @blopa

Regards

--- update - --

There is nothing in the log folder.

**Comment by blopa** [comment]
Hello. I'll look into it. Since this is a differente issue, please open a new issue. I'll close this one.
