### ISSUE TITLE
Include Path Issue

### ISSUE THREAD

**Issue by woelig** [blopa/Magento-Chatbot#61]
Hello,

I also have setup your extension for Facebook Chat Bot. I have filled all the information. Now I am facing problem in accessing the url with the custom key.

After making a call to http://www.website.com/chatbot/chatdata/facebook/key/69398037409
I get the following PHP error
Fatal error: require_once(): Failed opening required 'Api/witAI/witAI.php' (include_path='/var/www/htdocs/lib/minify:/var/www/htdocs/includes/src:.:/usr/local/lib/php') in /var/www/htdocs/includes/src/Werules_Chatbot_Model_Chatdata.php on line 7

If I view my var/log/system.log it's basically the same problem
2017-06-20T16:33:41+00:00 ERR (3): Warning: require_once(Api/witAI/witAI.php): failed to open stream: No such file or directory  in /var/www/htdocs/includes/src/Werules_Chatbot_Model_Chatdata.php on line 7
2017-06-20T16:33:54+00:00 ERR (3): Warning: require_once(Api/witAI/witAI.php): failed to open stream: No such file or directory  in /var/www/htdocs/includes/src/Werules_Chatbot_Model_Chatdata.php on line 7

Any idea on how to fix this? Oh and great work on this :)

**Comment by woelig** [comment]
This error occurs after running shell/compiler.php compile

**Comment by blopa** [comment]
Hello. Thank you for submitting this issue. Have you tried using the extensions without running shell/compiler?

**Comment by woelig** [comment]
Hello Blopa,

I managed to get it working with the bot responding :) when clearing the compiled data. But after the files is compiled it starts giving issues.

**Comment by woelig** [comment]
I have a second issue also if interested can log that one also.

**Comment by blopa** [comment]
Could you clarify exactly what you did? It might help others in the future.

**Comment by blopa** [comment]
I'm gonna close this for now. Feel free to open a new issue if you need help.
