### ISSUE TITLE
list_categories not working

### ISSUE THREAD

**Issue by woelig** [blopa/Magento-Chatbot#62]
Hello,

So I managed to setup Facebook Chat Bot communicating (uncompiled issue 61) but it stops responding after running list_categories

![image](https://user-images.githubusercontent.com/29579568/27431334-7d1e850c-574c-11e7-9bc9-63970328496a.png)

Magento Setup on my side is multi store with configurable products.

**Comment by blopa** [comment]
Hello. Thanks for submitting this issue.

Does the category listing works? How many categories does your store have? This might need some extra debugging.

The module isn't compatible with configurable products for now. Don't you have simple products?

**Comment by blopa** [comment]
I'm gonna close this for now. Feel free to open a new issue if you need help.
