### ISSUE TITLE
Something went wrong Error

### ISSUE THREAD

**Issue by bloggerpact** [blopa/Magento-Chatbot#65]
the bot was working fine but I sent a checkout command, after it started to give me an error. also I checked there is nothing inside log folder. 

![image](https://user-images.githubusercontent.com/22036537/27796432-941978e6-6027-11e7-9739-54d36742fcb0.png)

In waiting for your quick response. @blopa

Regards

**Comment by bloggerpact** [comment]
The problem has been solved, the command was stuck, which caused an error

**Comment by blopa** [comment]
It might not be a technical issue, but it's still a usability issue. I'll work on that. I'll reply your e-mail later today.
