### ISSUE TITLE
not displaying newly added products

### ISSUE THREAD

**Issue by bloggerpact** [blopa/Magento-Chatbot#66]
I've added some products to the website, but the bot is not displaying those products, I've refreshed all the cache and re-indexed. is there any way to refresh products data in bot database?

![image](https://user-images.githubusercontent.com/22036537/28088577-b642841c-66a3-11e7-9882-7122b45f6a36.png)

in waiting for quick response @blopa thanks in advance

Regards,

**Comment by blopa** [comment]
Hello. Sorry for the late reply. Are you using configurable products?

**Comment by bloggerpact** [comment]
no! i m using simple products with custom options

**Comment by blopa** [comment]
Got it. Yeah, we currently don't support custom options :( I'm trying to find time to work on this feature. I'm going to close this for now.

**Comment by thomas-thaulow** [comment]
Hello @blopa , found out anything about configurable products yet? Any toughts about how you would like to solve it? 

- Thomas

**Comment by blopa** [comment]
Hello. I have never worked with configurable products before, so I'm not sure. Products with Custom Option should come first, and then configurable products.

**Comment by thomas-thaulow** [comment]
@blopa really, my impression is that more people are using configurable then option? How long time do you think it would take to develop something like that?

**Comment by blopa** [comment]
@CiaraCode I really don't know. I was hoping that someone could help me out, since it's open source. That still didn't happened... so I don't know, I have to study more about CP to understand what can be done.

**Comment by thomas-thaulow** [comment]
Are we talking hours, days or months? I dont think I would have enough skills for it but I can for sure pay to get a developer to use some hours and help out to make it a reality. I really want to use this extension, but I only have configurable products as im running a clothing brand. 

If you can give me some more specific things you need help with I can pay for some hours with dev! :)

**Comment by blopa** [comment]
Well if you could pay for someone to develop it and are willing to put the code here in this repository, I for sure can help. You can easily find a developer on oDesk or freelancer.

**Comment by blopa** [comment]
@bloggerpact I just released a branch with a feature to display any kind of products on product search or categories. It's still not possible to add it to the cart, but at least you can show them on the chatbot.

https://github.com/blopa/Magento-Chatbot/tree/feature/all_products_types

Please try it and lemme know.

**Comment by bloggerpact** [comment]
I'll update the plugin and will let you know. Thanks for update @blopa
