### ISSUE TITLE
Just two questions

### ISSUE THREAD

**Issue by etsanov** [blopa/Magento-Chatbot#67]
I appreciate your work, and I just wanted to ask:

1) can this chatbot be used for abandoned cart messages in FB messenger
2) will it work for configurable products soon?

Thanks a bunch and keep up the good work!!!

**Comment by thomas-thaulow** [comment]
Would also like to know! But also is it possible that customers can select chat with a staff in meny also?

**Comment by blopa** [comment]
@etsanov Hello there. Abandoned cart is a really great idea, I haven't thought about that. That should be easy to implement, I'll look into that. As for the configurable products, I'm not sure. Products with Custom Option should come first, and then configurable products, I have never worked with it so I'm going to need more time.

@CiaraCode Hello. By "meny" ou mean "menu"? If so, that should be easily done using your theme /magento configuration by adding a link to your main menu.

**Comment by thomas-thaulow** [comment]
@blopa What I mean is when someone initiates a chat on messenger, would it be possible to give the customer the option to "see products, sign in, or chat with support on messenger?

**Comment by blopa** [comment]
@CiaraCode got it. That should be easy to do. Gonna work on that in the next days.

**Comment by thomas-thaulow** [comment]
Most people think bots are innovative and cool, but when it makes it impossible to chat with a real life human people will be mad. I believe thats why most people dont use bots today, because you have to choose either bot or human chat. If we can give the customer the option to talk to a human on messenger when initiating chat with bot, it would be alot easier to roll out the use of bots! :D 

Looking forward seeing it, really great module you have made here! :D

**Comment by blopa** [comment]
@etsanov Abandoned Cart is now implemented on #69 .
@CiaraCode Welcome Message Menu (Options) is now implemented on #68 .

As for the configurable products/custom option products, that should take some more time. Please lemme know if any of you are willing to pay a developer to help me out.

For now I'm closing this issue.

**Comment by thomas-thaulow** [comment]
@blopa Trying to find a developer. The usual devs I work with are not available atm, tried Freelancer but so much bad developers.... Will continue to try find a dev. 
Could you maybe send me a couple lines about what needs to be done or what they must check in order to make this work so I can use that when talking to them? 

Thanks!

**Comment by blopa** [comment]
The main problem is the function addProd2Cart() https://github.com/blopa/Magento-Chatbot/blob/master/Magento1/app/code/community/Werules/Chatbot/Model/Chatdata.php#L167

This functions as it's now, can only add simple products to the cart. So everytime I display a product using the bot (listing products, search, etc) I first check if its a simple product (as you can see here https://github.com/blopa/Magento-Chatbot/blob/master/Magento1/app/code/community/Werules/Chatbot/Model/Api/Facebook/Handler.php#L689 ) so first we have to refactor the function addProd2Cart() and then remove all those "simple product" validations. 

I'd say that this job description would be something like:

> I'm looking for a developer with experience in Magento 1.x to evolve a Open Source project on GitHub. There's a project on Github that integrates Magento and Facebook Messenger. Currently it only works with Simple Products with NO custom options and I need it to work with both.
> 
> Challenges:
> Make the module work with both Telegram and Facebook Messenger (que same function is used in both scenarios)
> Make the code clean
> User Magento coding conventions
> Code must be submitted as a Pull Request on the original project
> 
> Advantages:
> Fast Payment
> Help the Community
> The module developer are willing to help with this project

**Comment by blopa** [comment]
@etsanov and @CiaraCode I just released a branch with a feature to display any kind of products on product search or categories. It's still not possible to add it to the cart, but at least you can show them on the chatbot.

https://github.com/blopa/Magento-Chatbot/tree/feature/all_products_types

Please try it and lemme know.
