### ISSUE TITLE
Something went wrong, please try again. 

### ISSUE THREAD

**Issue by thomas-thaulow** [blopa/Magento-Chatbot#71]
Hello! 

Tried setting up default replies, tried all options possible and I only get: 
"Something went wrong, please try again." all the time. Anyone experiencing this issue? - Thomas

**Comment by thomas-thaulow** [comment]
Even login gives the error, did not give the error before

**Comment by blopa** [comment]
That's odd. Did you checked the log files?

**Comment by thomas-thaulow** [comment]
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: referral  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 243
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: postback  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 248
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: quick_reply  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 253
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: hub_verify_token  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 28
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: message  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 213
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: message  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 263
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: message  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 268
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: message  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 273
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: referral  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 243
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: postback  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 248
2017-09-13T04:01:14+00:00 ERR (3): Notice: Undefined index: message  in /var/www/ciaracode/app/code/community/Werules/Chatbot/Model/Api/Facebook/Messenger.php on line 253

**Comment by thomas-thaulow** [comment]
@blopa help and about works, all other commands gives error..

**Comment by thomas-thaulow** [comment]
@blopa any idea?

**Comment by blopa** [comment]
Can you send me the log from the module?

**Comment by blopa** [comment]
@CiaraCode can you send me the custom log from the chatbot module?

**Comment by thomas-thaulow** [comment]
@blopa What log file are you refering to? Only one I found in root/Var/log/  was messages and it only said: 
Sep 29 00:40:01 ciaracode systemd: Starting Session 398894 of user ciaracode.
Sep 29 00:40:01 ciaracode systemd: Started Session 398892 of user ciaracode.
Sep 29 00:40:01 ciaracode systemd: Starting Session 398892 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Started Session 398895 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Starting Session 398895 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Started Session 398896 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Starting Session 398896 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Started Session 398897 of user ciaracode.
Sep 29 00:41:01 ciaracode systemd: Starting Session 398897 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Started Session 398899 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Starting Session 398899 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Started Session 398898 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Starting Session 398898 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Started Session 398900 of user ciaracode.
Sep 29 00:42:01 ciaracode systemd: Starting Session 398900 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Started Session 398901 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Starting Session 398901 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Started Session 398902 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Starting Session 398902 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Started Session 398903 of user ciaracode.
Sep 29 00:43:01 ciaracode systemd: Starting Session 398903 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Started Session 398904 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Starting Session 398904 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Started Session 398906 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Starting Session 398906 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Started Session 398905 of user ciaracode.
Sep 29 00:44:01 ciaracode systemd: Starting Session 398905 of user ciaracode.
Sep 29 00:44:35 ciaracode systemd: Started Session 398907 of user ciaracode.
Sep 29 00:44:35 ciaracode systemd-logind: New session 398907 of user ciaracode.
Sep 29 00:44:35 ciaracode systemd: Starting Session 398907 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Started Session 398908 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Starting Session 398908 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Started Session 398910 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Starting Session 398910 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Started Session 398909 of user ciaracode.
Sep 29 00:45:01 ciaracode systemd: Starting Session 398909 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Started Session 398911 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Starting Session 398911 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Started Session 398912 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Starting Session 398912 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Started Session 398913 of user ciaracode.
Sep 29 00:46:01 ciaracode systemd: Starting Session 398913 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Started Session 398915 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Starting Session 398915 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Started Session 398914 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Starting Session 398914 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Started Session 398916 of user ciaracode.
Sep 29 00:47:01 ciaracode systemd: Starting Session 398916 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Started Session 398917 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Starting Session 398917 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Started Session 398918 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Starting Session 398918 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Started Session 398919 of user ciaracode.
Sep 29 00:48:01 ciaracode systemd: Starting Session 398919 of user ciaracode.
Sep 29 00:48:02 ciaracode systemd: Started Session 398920 of user ciaracode.
Sep 29 00:48:02 ciaracode systemd: Starting Session 398920 of user ciaracode.
Sep 29 00:48:02 ciaracode systemd-logind: New session 398920 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Started Session 398921 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Starting Session 398921 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Started Session 398923 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Starting Session 398923 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Started Session 398922 of user ciaracode.
Sep 29 00:49:02 ciaracode systemd: Starting Session 398922 of user ciaracode.

**Comment by thomas-thaulow** [comment]
In Magento root/var/log I ahve chatbot_facebook.log with: 

2017-09-28T22:46:28+00:00 DEBUG (7): Post Data:
array (
  'object' => 'page',
  'entry' => 
  array (
    0 => 
    array (
      'id' => '1691125637817174',
      'time' => 1506638788240,
      'messaging' => 
      array (
        0 => 
        array (
          'sender' => 
          array (
            'id' => '1485694264799106',
          ),
          'recipient' => 
          array (
            'id' => '1691125637817174',
          ),
          'timestamp' => 1506638788236,
          'delivery' => 
          array (
            'mids' => 
            array (
              0 => 'mid.$cAAYCEZ2_gmtk-_C93Veyqt1LJPDh',
            ),
            'watermark' => 1506638788061,
            'seq' => 0,
          ),
        ),
      ),
    ),
  ),
)


2017-09-28T22:46:29+00:00 DEBUG (7): Post Data:
array (
  'object' => 'page',
  'entry' => 
  array (
    0 => 
    array (
      'id' => '1691125637817174',
      'time' => 1506638788391,
      'messaging' => 
      array (
        0 => 
        array (
          'sender' => 
          array (
            'id' => '1485694264799106',
          ),
          'recipient' => 
          array (
            'id' => '1691125637817174',
          ),
          'timestamp' => 1506638788371,
          'delivery' => 
          array (
            'mids' => 
            array (
              0 => 'mid.$cAAYCEZ2_gmtk-_C93Veyqt1LJPDh',
            ),
            'watermark' => 1506638788061,
            'seq' => 0,
          ),
        ),
      ),
    ),
  ),
)


2017-09-28T22:46:31+00:00 DEBUG (7): Post Data:
array (
  'object' => 'page',
  'entry' => 
  array (
    0 => 
    array (
      'id' => '1691125637817174',
      'time' => 1506638788238,
      'messaging' => 
      array (
        0 => 
        array (
          'sender' => 
          array (
            'id' => '1691125637817174',
          ),
          'recipient' => 
          array (
            'id' => '1485694264799106',
          ),
          'timestamp' => 1506638788061,
          'message' => 
          array (
            'is_echo' => true,
            'app_id' => 1594960204166355,
            'mid' => 'mid.$cAAYCEZ2_gmtk-_C93Veyqt1LJPDh',
            'seq' => 850239,
            'text' => 'Something went wrong, please try again.',
          ),
        ),
      ),
    ),
  ),
)


2017-09-28T22:49:38+00:00 DEBUG (7): Post Data:
array (
  'object' => 'page',
  'entry' => 
  array (
    0 => 
    array (
      'id' => '1691125637817174',
      'time' => 1506638978208,
      'messaging' => 
      array (
        0 => 
        array (
          'sender' => 
          array (
            'id' => '1485694264799106',
          ),
          'recipient' => 
          array (
            'id' => '1691125637817174',
          ),
          'timestamp' => 1506638978193,
          'read' => 
          array (
            'watermark' => 1506638788061,
            'seq' => 0,
          ),
        ),
      ),
    ),
  ),
)

**Comment by blopa** [comment]
I'll have to check further into this, please send me an email so we can talk more about debugging this.

http://www.pablomontenegro.com.br/contato/

**Comment by thomas-thaulow** [comment]
@blopa Not heard anything frmo you, did you get my email?

**Comment by thomas-thaulow** [comment]
Tried adding you on facebook to to give you access to bot! :)

**Comment by thomas-thaulow** [comment]
@blopa I believe this issue can be closed, as its related to the depprecated version.
