### ISSUE TITLE
Improvements?

### ISSUE THREAD

**Issue by thomas-thaulow** [blopa/Magento-Chatbot#72]
Wouldnt this be a good idea? Get started button when starting messenger, then a welcome message with option to chat with support or search for products, etc? 

<img width="1084" alt="skjermbilde 2017-09-13 kl 11 57 27" src="https://user-images.githubusercontent.com/23300265/30371420-cfb1eefc-987a-11e7-9d96-2a9805177014.png">

**Comment by blopa** [comment]
That's already done. Please check version v0.0.16 the "Add options/commands to Welcome Message" option.
