### ISSUE TITLE
proper License

### ISSUE THREAD

**Issue by Flyingmana** [blopa/Magento-Chatbot#75]
Hey, providing it for Free is great, and sorry to nag with this topic.

But you may reach a point, where you need to decide for a proper license, and then things get complicated(from a legal perspective) if you already had several contributions.

The problem is, you need the ok from others, if you want to put their contributions under a different license.

**Comment by blopa** [comment]
Thank you for your feedback, @Flyingmana. For now I'm the only one maintaining this project. I think there are still a lot of features and module-architecture improvements to make it attractive for other developers to jump in it.

With that said, I'm open for changing the license for something that would make more sense for this project. Should I go with CC?

**Comment by Flyingmana** [comment]
CC would probably be ok

Magento itself suggest OSL, which it uses itself for the OpenSource part of Magento.
Recently they also recommend the MIT license for new modules. (which is used by most Open Source Projects nowdays, like Symfony, Doctrine, and since last week also the React ecosystem)

Keep in mind, that this is directly allowing to use it in any commercial context.(that may be clear for any of them, just wanted to note it)

I personally usually use the MIT license usually.

**Comment by blopa** [comment]
Thank you for your help.

I just added MIT license to the project, check https://github.com/blopa/Magento-Chatbot/pull/77

I'm aware people are going to use this for commercial use. I use Magento all the time, I like to think that with this module I can kind of give back some good features for the Magento Community who helped me for so many years.

Best.
