### ISSUE TITLE
Order Notifications on facebook

### ISSUE THREAD

**Issue by bloggerpact** [blopa/Magento-Chatbot#76]
I appreciate your work, I have a feature request it would be great if you add feature that can send order notifications direct on messenger. notifications such as order shipment,  when order status change, invoice update etc.
![image](https://user-images.githubusercontent.com/22036537/31088735-5cbbea66-a7bf-11e7-9af1-ae94b96fe3cd.png)

![image](https://user-images.githubusercontent.com/22036537/31088792-895097fc-a7bf-11e7-9f22-1a175bb4a7fc.png)

@blopa Thanks a bunch and keep up the good work!

**Comment by blopa** [comment]
Hello @bloggerpact.
That is a good idea for a feature, indeed. Is that from a existing module? Can you share it?

**Comment by bloggerpact** [comment]
Yes, this is an existing module, but it is a subscription-based has lot of features like answering each message and commen but would be great if you include only notifications related with orders  https://marketplace.magento.com/magetrend-mt-messenger.html @blopa

**Comment by blopa** [comment]
I can't promise you a date, but I'll work on that.

**Comment by bloggerpact** [comment]
Thanks :+1: Will wait for this feature
