### ISSUE TITLE
Not Showing On Home Page

### ISSUE THREAD

**Issue by webixpk** [blopa/Magento-Chatbot#78]
Hello 
I have installed it on my website but it is not showing on homepage. http://new.mojari.com.pk/

**Comment by blopa** [comment]
Hello. By "not showing on homepage" you mean the  "Facebook Live Chat on store frontend" feature?

![img](https://i.imgur.com/HgizUwg.png)

Did you enabled it on backend panel?

**Comment by webixpk** [comment]
Hello 
http://new.mojari.com.pk/ this is my website homepage, chatbot is not showing on it, but it is showing on all inner pages like http://new.mojari.com.pk/index.php/contacts
Means chatbot is showing and working on all pages except my website homepage.

**Comment by blopa** [comment]
That's weird. There's probably a block on your homepage that it's rewriting the module's block.
