### ISSUE TITLE
Modman support

### ISSUE THREAD

**Issue by bloggerpact** [blopa/Magento-Chatbot#81]
As u know that Magento has closed its legacy version of the market for version 1.x. Why don't you add modman for easy installing/Upgrading. 
https://github.com/colinmollenhour/modman/wiki/Tutorial

**Comment by blopa** [comment]
Hello @bloggerpact.

You're right, it's important to add Modman support. I'll work on that in the next version.

**Comment by bloggerpact** [comment]
Hello @blopa 
You already working on a newer version of magento 1.x Magento Chatbot and its a good time to include modman support in this newer version so that we can test and upgrade time to time.
